In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import blimpy as bl
from blimpy import Waterfall
from pathlib import Path
import os

# Mars Inventory Csv:

In [5]:
midres_dir = Path("/datag/blpd18/datax/gb_mars/splices")

rows = []

for f in sorted(midres_dir.glob("*.0002.fil")):
    wf = Waterfall(str(f), load_data=False)
    h = wf.header
    
    rows.append({
        "file": f.name,
        "source": h.get("source_name"),
        "nchans": h["nchans"],
        "foff_Hz": h["foff"] * 1e6,  # MHz -> Hz
        "tsamp_s": h["tsamp"],
        "fch1_MHz": h["fch1"],
        "bandwidth_MHz": abs(h["foff"]) * h["nchans"]
    })

df = pd.DataFrame(rows)

df

,file,source,nchans,foff_Hz,tsamp_s,fch1_MHz,bandwidth_MHz
0,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1310720,-2861.022949,1.073742,11251.464844,3750.0
1,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1310720,-2861.022949,1.073742,11251.464844,3750.0
2,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1310720,-2861.022949,1.073742,11251.464844,3750.0
3,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1310720,-2861.022949,1.073742,11251.464844,3750.0
4,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1310720,-2861.022949,1.073742,11251.464844,3750.0
5,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1310720,-2861.022949,1.073742,11251.464844,3750.0

In [6]:
narrow_dir = Path("/datag/blpd18/datax/gb_mars/single_coarse_channel")

rows = []

for f in sorted(narrow_dir.glob("*.h5")):
    wf = Waterfall(str(f), load_data=False)
    h = wf.header
    
    rows.append({
        "file": f.name,
        "source": h.get("source_name"),
        "nchans": h["nchans"],
        "foff_Hz": h["foff"] * 1e6,
        "tsamp_s": h["tsamp"],
        "fch1_MHz": h["fch1"],
        "bandwidth_MHz": abs(h["foff"]) * h["nchans"]
    })

narrow_df = pd.DataFrame(rows)

narrow_df

,file,source,nchans,foff_Hz,tsamp_s,fch1_MHz,bandwidth_MHz
0,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1048576,-2.793968,18.253611,8415.527344,2.929688
1,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1048576,-2.793968,18.253611,8415.527344,2.929688
2,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1048576,-2.793968,18.253611,8415.527344,2.929688
3,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1048576,-2.793968,18.253611,8415.527344,2.929688
4,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars2020,1048576,-2.793968,18.253611,8415.527344,2.929688
5,spliced_blc10111213141516o7o0212223242526o7o03...,DIAG_Mars,1048576,-2.793968,18.253611,8415.527344,2.929688

In [3]:

for f in sorted(Path("/datag/blpd18/datax/gb_mars/splices").glob("*.0002.fil")):
    wf = Waterfall(str(f), load_data=False)
    h = wf.header

    print(f.name)
    print("  source :", h.get("source_name"))
    print("  nchans :", h["nchans"])
    print("  foff   :", h["foff"])
    print("  tsamp  :", h["tsamp"])
    print("  fch1   :", h["fch1"])
    print()

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66265_DIAG_Mars2020_0011.rawspec.0002.fil
  source : DIAG_Mars2020
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66578_DIAG_Mars_0012.rawspec.0002.fil
  source : DIAG_Mars
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66892_DIAG_Mars2020_0013.rawspec.0002.fil
  source : DIAG_Mars2020
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67205_DIAG_Mars_0014.rawspec.0002.fil
  source : DIAG_Mars
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67519_DIAG_Mars2020_0015.rawspec.0002.fil
  source : DIAG_Mars2020
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67832_DIAG_Mars_0016.rawspec.0002.fil
  source : DIAG_Mars
  nchans : 1310720
  foff   : -0.00286102294921875
  tsamp  : 1.073741823999999
  fch1   : 11251.46484375

# Quick Look Plots:

In [7]:
mid_file = "/datag/blpd18/datax/gb_mars/splices/spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66265_DIAG_Mars2020_0011.rawspec.0002.fil"

narrow_file = "/datag/blpd18/datax/gb_mars/single_coarse_channel/spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66265_DIAG_Mars2020_0011.rawspec.0000_diced.h5"

In [8]:
mid = Waterfall(mid_file, load_data=False)
nar = Waterfall(narrow_file, load_data=False)

print(mid.header)
print(nar.header)

{'machine_id': 20, 'telescope_id': 6, 'data_type': 1, 'fch1': 11251.46484375, 'foff': -0.00286102294921875, 'nchans': 1310720, 'source_name': 'DIAG_Mars2020', 'src_raj': <Angle 0. hourangle>, 'src_dej': <Angle 0. deg>, 'az_start': 0.0, 'za_start': 0.0, 'nbits': 32, 'tstart': 59256.76695601852, 'tsamp': 1.073741823999999, 'nifs': 1}
{'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': np.float64(0.0), 'data_type': np.int64(1), 'fch1': np.float64(8415.52734375), 'foff': np.float64(-2.7939677238464355e-06), 'machine_id': np.int64(20), 'nbits': np.int64(32), 'nchans': np.int64(1048576), 'nifs': np.int64(1), 'source_name': 'DIAG_Mars2020', 'src_dej': <Angle 0. deg>, 'src_raj': <Angle 0. hourangle>, 'telescope_id': np.int64(6), 'tsamp': np.float64(18.253611007999982), 'tstart': np.float64(59256.76695601852), 'za_start': np.float64(0.0)}

In [9]:
mid_data = Waterfall(mid_file).data
nar_data = Waterfall(narrow_file).data

print(mid_data.shape)
print(nar_data.shape)

(279, 1, 1310720)
(16, 1, 1048576)

In [ ]:
mid_freq = (
    mid.header["fch1"]
    + np.arange(mid.header["nchans"]) * mid.header["foff"]
)

nar_freq = (
    nar.header["fch1"]
    + np.arange(nar.header["nchans"]) * nar.header["foff"]
)

print(mid_freq[0], mid_freq[-1])
print(nar_freq[0], nar_freq[-1])

11251.46484375 7501.467704772949
8415.52734375 8412.597659043968

In [23]:
freq_min = nar_freq.min()
freq_max = nar_freq.max()

mask = (mid_freq >= freq_min) & (mid_freq <= freq_max)

mid_indices = np.where(mask)[0]

mid_crop = mid_data[:, mid_indices]

print(mid_crop.shape)


print(mid_indices[0], mid_indices[-1])
print(len(mid_indices))

(279, 1024)
991232 992255
1024

In [21]:
print(mid_data.shape)
print(nar_data.shape)

print(mid_data.shape)

factor = mid_data.shape[0] // nar_data.shape[0]

print(factor)

mid_crop_avg = mid_crop[:16*factor].reshape(
    16,
    factor,
    -1
).mean(axis=1)

print(mid_crop_avg.shape)

(279, 1310720)
(16, 1048576)
(279, 1310720)
17

NameError: name 'mid_crop' is not defined

# Average Spectrum:

# Brightest Channel Track:

# Independent Drift Fitting

# Bliss Comparison: